export const INGRIDIENTS_REQUEST: 'INGRIDIENTS_REQUEST' = 'INGRIDIENTS_REQUEST';
export const INGRIDIENTS_FAILED: 'INGRIDIENTS_FAILED' = 'INGRIDIENTS_FAILED';
export const INGRIDIENTS_SUCCESS: 'INGRIDIENTS_SUCCESS' = 'INGRIDIENTS_SUCCESS';
export const ADD_INGRIDIENT: 'ADD_INGRIDIENT' = 'ADD_INGRIDIENT';
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';
export const MOVE_INGRIDIENT: 'MOVE_INGRIDIENT' = 'MOVE_INGRIDIENT';
export const DELETE_INGRIDIENT: 'DELETE_INGRIDIENT' = 'DELETE_INGRIDIENT'

export const WS_CONNECTION_START: 'WS_CONNECTION_START'  = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_ORDERS_DATA: 'WS_GET_ORDERS_DATA' = 'WS_GET_ORDERS_DATA';
export const WS_SEND_ORDERS: 'WS_SEND_ORDERS' = 'WS_SEND_ORDERS';
export const WS_CLOSE_ORDERS_SOCKET: 'CLOSE_ORDERS_SOCKET' = 'CLOSE_ORDERS_SOCKET';

export const OPEN_INGRIDIENT_REQUEST: 'OPEN_INGRIDIENT_REQUEST' = 'OPEN_INGRIDIENT_REQUEST';
export const OPEN_INGRIDIENT_SUCCESS: 'OPEN_INGRIDIENT_SUCCESS' = 'OPEN_INGRIDIENT_SUCCESS';
export const CLOSE_INGRIDIENT: 'CLOSE_INGRIDIENT' = 'CLOSE_INGRIDIENT';


export const ORDER_REQUEST: 'ORDER_REQUEST' = 'ORDER_REQUEST';
export const ORDER_SUCCESS: 'ORDER_SUCCESS' = 'ORDER_SUCCESS';
export const ORDER_FAILED: 'ORDER_FAILED' = 'ORDER_FAILED';
export const ORDER_CLOSE: 'ORDER_CLOSE' = 'ORDER_CLOSE';

export const SET_POPUP_ACITVE = 'SET_MODAL_ACTIVE'
export const SET_POPUP_CLOSE = 'SET_MODAL_CLOSE'


export const FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST' = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS' = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILED: 'FORGOT_PASSWORD_FAILED' = 'FORGOT_PASSWORD_FAILED'

export const RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST' = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED' = 'RESET_PASSWORD_FAILED'


export const REGISTER_FORM_REQUEST = 'REGISTER_FORM_REQUEST';
export const REGISTER_FORM_SUCCESS = 'REGISTER_FORM_SUCCESS';
export const REGISTER_FORM_FAILED = 'REGISTER_FORM_FAILED';

export const LOGIN_FORM_REQUEST: 'LOGIN_FORM_REQUEST' = 'LOGIN_FORM_REQUEST';
export const LOGIN_FORM_SUCCESS: 'LOGIN_FORM_SUCCESS' = 'LOGIN_FORM_SUCCESS'
export const LOGIN_FORM_FAILED: 'LOGIN_FORM_FAILED' = 'LOGIN_FORM_FAILED'


export const GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST' = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS' = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAILED: 'GET_PROFILE_FAILED' = 'GET_PROFILE_FAILED'

export const PATCH_PROFILE_REQUEST: 'PATCH_PROFILE_REQUEST' = 'PATCH_PROFILE_REQUEST'
export const PATCH_PROFILE_SUCCESS: 'PATCH_PROFILE_SUCCESS' = 'PATCH_PROFILE_SUCCESS'
export const PATCH_PROFILE_FAILED: 'PATCH_PROFILE_FAILED' = 'PATCH_PROFILE_FAILED'


export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS'