export const INGRIDIENTS_REQUEST: 'INGRIDIENTS_REQUEST' = 'INGRIDIENTS_REQUEST';
export const INGRIDIENTS_FAILED: 'INGRIDIENTS_FAILED' = 'INGRIDIENTS_FAILED';
export const INGRIDIENTS_SUCCESS: 'INGRIDIENTS_SUCCESS' = 'INGRIDIENTS_SUCCESS';
export const ADD_INGRIDIENT: 'ADD_INGRIDIENT' = 'ADD_INGRIDIENT';
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';
export const MOVE_INGRIDIENT: 'MOVE_INGRIDIENT' = 'MOVE_INGRIDIENT';
export const DELETE_INGRIDIENT: 'DELETE_INGRIDIENT' = 'DELETE_INGRIDIENT'